### ISSUE TITLE
automatic (configurable) time-to-deletion

### ISSUE THREAD

**Issue by alfredodeza** [ceph/chacra#109]
_From @alfredodeza on May 24, 2016 19:3_

Binaries are huge, and for testing purposes there is no need to keep every binary and every repository built.

A configurable value (that defaults to two weeks) should be allowed to destroy a sha1/refs for a given project.

_Copied from original issue: ceph/mita#75_

**Comment by alfredodeza** [comment]
_From @ktdreyer on May 24, 2016 19:30_

:+1: this would be awesome.

**Comment by dmick** [comment]
Perhaps something like git's gc: a combination of time and "are there refs that point here"
