### ISSUE TITLE
`ref` should be able to understand what `sha1` has it built

### ISSUE THREAD

**Issue by alfredodeza** [ceph/chacra#111]
_From @alfredodeza on May 24, 2016 18:55_

This presents a problem because the current URL structure is:

     project/ref/distro/distro_version/architecture/

So modifying this to accommodate sha1 (backwards incompatible) would look like 

     project/ref/sha1/distro/distro_version/architecture/

The other option would be to not make sha1 part of the url, but part of the API. That is, `ref` would need to be told about the `sha1` it is receiving, but this sounds problematic as the correctness would fully rely on the client and not the system. It would be tricky to ensure separation of sha1's across the board.

For example, when building a repository, code would need to be adapted to not mix different binaries from different sha1's.

I am not sure what is the best answer here, some users may not even want to have a sha1 in the url and that would be cumbersome to make it optional.

_Copied from original issue: ceph/mita#73_

**Comment by alfredodeza** [comment]
_From @ktdreyer on May 24, 2016 18:58_

I think it would be

```
 project/sha1/distro/distro_version/architecture/
```

(no `ref` there) right?

EDIT: I say this, because this is how gitbuilder is laid out currently.

**Comment by alfredodeza** [comment]
_From @zmc on May 24, 2016 19:13_

@ktdreyer, that's not quite right. Here are two example URLs:
http://gitbuilder.ceph.com/ceph-deb-trusty-x86_64-basic/ref/master/
http://gitbuilder.ceph.com/ceph-deb-trusty-x86_64-basic/sha1/0ba2e145d08b0560f155e30f643ce6cf6c5b763c/

I think we will need to be able to query for builds both by sha1, and by branch.

**Comment by alfredodeza** [comment]
Seems like gitbuilders have two different structures, one for refs and another one for sha1s:

    http://gitbuilder.ceph.com/ceph-rpm-fc22-x86_64-basic/ref/
    http://gitbuilder.ceph.com/ceph-rpm-fc22-x86_64-basic/sha1

For refs it includes a file named `sha1` to help understand what `sha1` that ref points to. For the `master` ref that would be:

    http://gitbuilder.ceph.com/ceph-rpm-fc22-x86_64-basic/ref/master/sha1

So that helps to answer "what is the sha1 this ref was built at?". However, for sha1's it includes the same file (nothing there to do a reverse mapping).

I believe that having the sha1 as part of the url would get rid of the problem, with the actual ability to do nifty things like adding `latest`:

     project/ref/latest/

**Comment by alfredodeza** [comment]
_From @ktdreyer on May 24, 2016 19:38_

> So that helps to answer "what is the sha1 this ref was built at?". However, for sha1's it includes the
> same file (nothing there to do a reverse mapping).

Right, I think this is because the ref "master" is just a symlink on disk to the sha1 directory on disk. It does look weird from an API perspective but it's "just a bunch of files".

**Comment by alfredodeza** [comment]
_From @zmc on May 24, 2016 19:43_

It'd be really helpful to also have the reverse mapping, i.e. sha1->branch. I realize that a given sha1 can be present in multiple branches, but at the time a build is initiated we *might* be able to assume it is only in one. Granted, that might invite a race condition

**Comment by ktdreyer** [comment]
@zmc what depends on the reverse mapping? it seems likely to me that multiple refs are going to refer to the same sha1 (eg `jewel` and `jewel-backports` and `v10.2.1`)

**Comment by dmick** [comment]
It would be nice to have "a way" (perhaps not chacra) to do "--contains".  I'm starting to wonder whether we couldn't very much use a web api to enhance Git ref <-> sha1 translation in general.

**Comment by zmc** [comment]
@ktdreyer Well, since we've never had it, nothing does. It would be a "nice to have" feature, but I can't think of anything we'd strictly need it for at the moment.

**Comment by alfredodeza** [comment]
@dmick why is it useful for a build system to know if a sha1 is contained in some other build? I am trying to figure out the use case here

**Comment by andrewschoen** [comment]
Currently we are using ``ref`` to mean either a branch or a tag in chacra. Why couldn't we use a sha1 as well?  Meaning, both of these would be valid:

```
project/67ac2253b73bf80475c63436f8b9e59353137b41/distro/distro_version/architecture/

project/master/distro/distro_version/architecture/

```

We could then add metadata to the Binary model to hold branch, tag and/or sha1. After a build and uploading of the binaries to chacra jenkins could update that metadata.

**Comment by dmick** [comment]
I don't think the build system cares.

**Comment by andrewschoen** [comment]
Did we decide to go with this structure? 

```
 project/ref/sha1/distro/distro_version/architecture/
```

This makes the most sense to me because we only care about a branch to sha1 mapping at the time of the build and uploading of the binary.

I think we might want to put that at a ``v2`` endpoint or something though as it's backwards incompatible.

**Comment by dmick** [comment]
the difficulty is that I think sometimes we'll want to at least query about ref/latest and about sha1.  I'm not sure that simple URL mappings are going to cover all the needs. 

But I also sense there's a much larger discussion to be had about use cases and requirements.

**Comment by alfredodeza** [comment]
@dmick this url structure doesn't allow queries though. We could have a 'latest' aliased to the last one built. The system that would allow queries is not this one (chacra).

@athanatos @gregsfortytwo do you guys think there is a use case for the tooling/systems to provide a strict relation of ref/sha1 *from* git vs. "this is the latest sha1 that was built"?

The idea (currently) is to build in a first-come-first-served basis, so "latest sha1" might not mean "latest sha1 in git". 

We need to nail this down to be able to move forward (regardless of the url structure here)

**Comment by dmick** [comment]
If there's no querying, then why worry about ref at all?  just use sha1

**Comment by athanatos** [comment]
@alfredodeza @dmick I guess it might be useful for something like master to allow us to determine what the newest master sha1 built is and schedule against that.  However, I think there's another important workflow (probably the more important one) where we check git for the sha1 of the branch and delay scheduling until it's built.

**Comment by dmick** [comment]
but if it's another service that handles queries, then it doesn't matter what this one is, just that it's unique

**Comment by gregsfortytwo** [comment]
Uh, I guess it depends on the rest of the model, which I don't really know. I think we will at some point need to be able to say "build the latest <x>, and schedule a run against it when done".
But for replacing our existing stuff, probably we just need to be able to resolve what sha1 a particular ref is. I really don't know enough about the existing stuff to be useful here; I want features and don't care about implementation. ;)

**Comment by athanatos** [comment]
@gregsfortytwo  The ref->sha1 mapping is a git/github thing, not a chacra thing.  The question is whether we need to be able to ask chacra something more than "is this sha1 built?" like "what is the newest built sha1 which is an ancestor of this other sha1?"

**Comment by dmick** [comment]
...but that latter question could also be answered with "ask git for a rev history, and then ask chacra for a specific sha1", and if Alfredo is compartmentalizing as much as it seems...

**Comment by athanatos** [comment]
Yeah, we could do that too.  I'm more interested in the use case where I'm trying to test a particular sha1 anyway than I am in trying to test "some recent master build".
