### ISSUE TITLE
The health check endpoint should check disk usage

### ISSUE THREAD

**Issue by andrewschoen** [ceph/chacra#201]
If shaman gives out a chacra node that has little disk space builds fail when trying to upload the binaries. We need some way to remove chacra nodes from the pool that are not capable of storing anymore binaries or repos.

At some point when those repos are auto deleted we'll need a mechanism for adding them back to the pool as well.

**Comment by alfredodeza** [comment]
Fixed with https://github.com/ceph/chacra/commit/71dbb68ca24a8fd7082851d108cab259e8dcac52
