### ISSUE TITLE
Repos in shaman and chacra is NULL while Finished is SUCCESS?

### ISSUE THREAD

**Issue by Songweibin** [ceph/chacra#225]
I make a run.py just like "[shaman/config/run.py](https://github.com/ceph/shaman/blob/master/config/run.py)" to run chacra.
After the Jenkins build finished with success, the Repos in shaman and chacra is NULL. Would you tell me why is this or how to start (setup) chacra. Thank you. @andrewschoen @alfredodeza 
The following is part of log:

+ cat /home/jenkins/workspace/ceph-dev-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/trusty/DIST/trusty/repo-extra.json
{
    "version":"12.0.0-810-gda06227",
    "package_manager_version":"12.0.0-810-gda06227-1trusty",
    "build_url":"http://jenkins.star.com.cn/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=trusty,DIST=trusty/97/",
    "root_build_cause":"MANUALTRIGGER",
    "node_name":"phy-10.118.203.10-ubuntu-trusty",
    "job_name":"ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=trusty,DIST=trusty"
}
+ cat /home/ubuntu/.chacractl
url = "http://192.168.34.252/"
user = "admin"
key = "secret"
ssl_verify = False
+ curl -X POST -H Content-Type:application/json --data @/home/jenkins/workspace/ceph-dev-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/trusty/DIST/trusty/repo-extra.json -u admin:secret http://192.168.34.252/repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/extra/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1198  100   771  100   427  15724   8708 --:--:-- --:--:-- --:--:-- 16062
{"project_name": "ceph", "extra": {"build_url": "http://jenkins.star.com.cn/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=trusty,DIST=trusty/97/", "root_build_cause": "MANUALTRIGGER", "version": "12.0.0-810-gda06227", "node_name": "phy-10.118.203.10-ubuntu-trusty", "job_name": "ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=trusty,DIST=trusty", "package_manager_version": "12.0.0-810-gda06227-1trusty"}, "distro_version": "trusty", "path": null, "flavor": "default", "size": 0, "needs_update": true, "sha1": "da06227c7fdd71936fc152e29551268e78541e21", "is_queued": false, "is_updating": false, "type": "deb", "modified": "2017-02-27 17:09:20.166290", "signed": false, "ref": "master", "archs": ["x86_64"], "distro": "ubuntu"}+ /tmp/venv.Dp0IvzuZV8/bin/chacractl repo update ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default
[requests.packages.urllib3.connectionpool][DEBUG ] Starting new HTTP connection (1): 192.168.34.252
[requests.packages.urllib3.connectionpool][DEBUG ] http://192.168.34.252:80 "HEAD /repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/update HTTP/1.1" 200 0
[chacractl.api.repos][INFO  ] POST: http://192.168.34.252/repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/update
[requests.packages.urllib3.connectionpool][DEBUG ] Starting new HTTP connection (1): 192.168.34.252
[requests.packages.urllib3.connectionpool][DEBUG ] http://192.168.34.252:80 "POST /repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/update HTTP/1.1" 200 771
[chacractl.api.repos][INFO  ] needs_update: True
[chacractl.api.repos][INFO  ] project_name: ceph
[chacractl.api.repos][INFO  ] is_queued: False
[chacractl.api.repos][INFO  ] is_updating: False
[chacractl.api.repos][INFO  ] extra: {u'build_url': u'http://jenkins.star.com.cn/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=trusty,DIST=trusty/97/', u'root_build_cause': u'MANUALTRIGGER', u'version': u'12.0.0-810-gda06227', u'node_name': u'phy-10.118.203.10-ubuntu-trusty', u'job_name': u'ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=trusty,DIST=trusty', u'package_manager_version': u'12.0.0-810-gda06227-1trusty'}
[chacractl.api.repos][INFO  ] ref: master
[chacractl.api.repos][INFO  ] modified: 2017-02-28 09:00:31.405657
[chacractl.api.repos][INFO  ] distro_version: trusty
[chacractl.api.repos][INFO  ] sha1: da06227c7fdd71936fc152e29551268e78541e21
[chacractl.api.repos][INFO  ] signed: False
[chacractl.api.repos][INFO  ] path: None
[chacractl.api.repos][INFO  ] flavor: default
[chacractl.api.repos][INFO  ] distro: ubuntu
[chacractl.api.repos][INFO  ] type: deb
[chacractl.api.repos][INFO  ] archs: [u'x86_64']
[chacractl.api.repos][INFO  ] size: 0
+ echo Check the status of the repo at: http://192.168.34.254/api/repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/
Check the status of the repo at: http://192.168.34.254/api/repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/
+ update_build_status completed ceph ubuntu trusty x86_64
+ state=completed
+ project=ceph
+ distro=ubuntu
+ distro_version=trusty
+ distro_arch=x86_64
+ submit_build_status POST completed ceph ubuntu trusty x86_64
+ http_method=POST
+ state=completed
+ project=ceph
+ distro=ubuntu
+ distro_version=trusty
+ distro_arch=x86_64
+ cat
+ cat
+ SHAMAN_URL=http://192.168.34.254/api/builds/ceph/
+ curl -X POST -H Content-Type:application/json --data @/home/jenkins/workspace/ceph-dev-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/trusty/DIST/trusty/build_status.json -u admin:secret http://192.168.34.254/api/builds/ceph/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   772  100     2  100   770    136  52441 --:--:-- --:--:-- --:--:-- 55000
{}+ rm -fr /tmp/install-deps.12694
Notifying upstream projects of job completion
Finished: SUCCESS

**Comment by andrewschoen** [comment]
The log here makes it look like the binaries were uploaded to chacra correctly.  What do you see at these endpoints? Checking these will let you know if the binaries have been uploaded and if the repo was created successfully.

http://192.168.34.252/repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/

http://192.168.34.252/binaries/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/

Also, for status to show up in shaman you need to configure it as a ``callback_url`` in chacra using this config option: https://github.com/ceph/chacra/blob/master/deploy/playbooks/roles/common/templates/prod_callbacks.py.j2#L3

That needs to be set to the ``api/repos/`` endpoint of your shaman node.

**Comment by Songweibin** [comment]
Thanks a lot. I can see these information in that two url:
{"project_name": "ceph", "extra": {"build_url": "http://jenkins.clove.zte.com.cn/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=trusty,DIST=trusty/109/", "root_build_cause": "MANUALTRIGGER", "version": "12.0.0-810-gda06227", "node_name": "phy-10.118.203.10-ubuntu-trusty", "job_name": "ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=trusty,DIST=trusty", "package_manager_version": "12.0.0-810-gda06227-1trusty"}, "distro_version": "trusty", "path": null, "flavor": "default", "size": 0, "needs_update": true, "sha1": "da06227c7fdd71936fc152e29551268e78541e21", "is_queued": false, "is_updating": false, "type": "deb", "modified": "2017-03-09 01:57:19.445524", "signed": false, "ref": "master", "archs": ["x86_64"], "distro": "ubuntu"}   
{"trusty": ["x86_64"]}    

And after setup `callback_url` in chacra, the Jinkens build failed with error code 500 :  
[requests.packages.urllib3.connectionpool][DEBUG ] Starting new HTTP connection (1): 192.168.34.252
[requests.packages.urllib3.connectionpool][DEBUG ] http://192.168.34.252:80 "HEAD /repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/update HTTP/1.1" 200 0
[chacractl.api.repos][INFO  ] POST: http://192.168.34.252/repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/update
[requests.packages.urllib3.connectionpool][DEBUG ] Starting new HTTP connection (1): 192.168.34.252
[requests.packages.urllib3.connectionpool][DEBUG ] http://192.168.34.252:80 "POST /repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/update HTTP/1.1" 500 7134
[chacractl][ERROR ] RuntimeError: POST for http://192.168.34.252/repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/update failed: 500 

+ rm -fr /tmp/install-deps.4386
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE

**Comment by alfredodeza** [comment]
@Songweibin an HTTP 500 means that there was an unhandled error in the Python app (chacra in this case). I would suggest looking at what the logs for chacra look for that POST url:

    [chacractl][ERROR ] RuntimeError: POST for http://192.168.34.252/repos/ceph/master/da06227c7fdd71936fc152e29551268e78541e21/ubuntu/trusty/flavors/default/update failed: 500
