### ISSUE TITLE
adding new distro versions for DEB repos doesn't recreate the file

### ISSUE THREAD

**Issue by alfredodeza** [ceph/chacra#97]
The code will only create the file if it doesn't exist, no way to force it to create one if modifying the templating.

**Comment by dmick** [comment]
Which file?

**Comment by andrewschoen** [comment]
Fixed in https://github.com/ceph/chacra/pull/99

**Comment by alfredodeza** [comment]
@dmick the distributions file. chacra creates that file given some values like distro names
